config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: {registrations: 'registrations'}
  get 'images/index'
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :images, only: [:index, :destroy, :update]
    resources :favs, only: [:index]
  end
  root 'users#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true

  validates_length_of :zip, is: 5,  message: "Zip must be 5 digit long"
  validates :city, :street, length: { in: 1..100, message: "Must be less than 100 characters" }, allow_blank: false
  validates_numericality_of :home_number, allow_nil: false,
                            only_integer: true, greater_than: 0, less_than: 5000, message: "Must be less than 5000 digits"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fav.rb
class Fav < ApplicationRecord
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :images, dependent: :destroy
  has_many :favs, dependent: :destroy
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address, update_only: true

  validates_associated :address

  validates :first_name, :last_name, length: { maximum: 100, message: "Must be less than 100 characters" }
  validates_numericality_of :age, allow_nil: true, only_integer: true, less_than_or_equal_to: 120, message: "Must be in range from 0 to 120"
  validates :about, length: { maximum: 300, message: "Must be less than 300 characters" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer
        .permit(:sign_up,
                keys: [:first_name,
                       :last_name,
                       :email,
                       :age,
                       :sex,
                       :about,
                       address_attributes: [:zip, :city, :street, :home_number]
                ]
        )
    devise_parameter_sanitizer
        .permit(:account_update,
                keys: [:first_name,
                       :last_name,
                       :email,
                       :age,
                       :sex,
                       :about,
                       address_attributes: [:zip, :city, :street, :home_number]
                ]
        )
  end
end

app/controllers/favs_controller.rb
class FavsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @all_urls = Fav.where(user_id: params[:user_id]).order(:id)
  end
end

app/controllers/images_controller.rb
require 'faker'
require 'net/http'
require 'uri'

class ImagesController < ApplicationController

  before_action :set_user, only: [:index, :update, :destroy]
  before_action :check_access, only: [:index, :update, :destroy]

  def index
    faker = Faker::LoremFlickr.image
    first_part = faker.slice"http://loremflickr.com"
    second_part = get_response_with_redirect(URI.parse(faker))
    @url = first_part + second_part

    @user.images.create(image_url: @url)
    
    @all_urls = Image.where(user_id: params[:user_id]).order(:id)
  end

  def get_response_with_redirect(uri)
    r = Net::HTTP.get_response(uri)
    if r.code == "301"
      r = Net::HTTP.get_response(URI.parse(r.header['location']))
      part_url = r.header['location']
    end
    part_url
  end

  def update
    @user = User.find(params[:user_id])
    @img_record = Image.find(params[:id])
    @user.favs.create(url: @img_record.image_url)
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to user_images_path
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end

  def check_access
    unless @user.id == current_user.id || current_user.is_admin?
      redirect_to root_path, :alert => "Access denied."
    end
    puts 'a'

    # unless @user == current_user
    #   redirect_to root_path, :alert => "Access denied."
    # end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    build_resource({})
    resource.build_address
    respond_with self.resource
  end
end

app/controllers/users_controller.rb
require 'faker'
require 'net/http'
require 'uri'

class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :show]
  before_action :check_access, only: [:edit, :update, :destroy, :show]

  def index
    @users = User.all.includes(:address)
    @user = current_user
    @all_urls = []

    if current_user == nil
      12.times do |x|
        faker = Faker::LoremFlickr.image
        first_part = faker.slice"http://loremflickr.com"
        second_part = get_response_with_redirect(URI.parse(faker))
        url = first_part + second_part
        @all_urls << url
      end
    end

    if params.has_key?(:Male)
      @users = User.where("sex = :sex", {sex: "Male"})
    elsif params.has_key?(:Female)
      @users = User.where("sex = :sex", {sex: "Female"})
    elsif params.has_key?(:Other)
      @users = User.where("sex = :sex", {sex: "Other"})
    end

    if params.has_key?(:from) && params.has_key?(:to)
      @users = User.where("age BETWEEN ? AND ?", params.values_at(:from)[0], params.values_at(:to)[0]).order(age: :asc)
    end

    if params.has_key?(:sort_by_names) && params.has_value?("1")
      @users = @users.order(first_name: :asc)
    elsif params.has_key?(:sort_by_names) && params.has_value?("2")
      @users = @users.order(last_name: :asc)
    end

    @addr = Address.all.order(city: :asc).uniq.pluck(:city)

    if params.has_key?(:sort_by_cities)
      @users = @users.joins(:address).includes(:address).where("addresses.city = ?", params.values_at(:sort_by_cities)[0])
    end


  end

  def get_response_with_redirect(uri)
    r = Net::HTTP.get_response(uri)
    if r.code == "301"
      r = Net::HTTP.get_response(URI.parse(r.header['location']))
      part_url = r.header['location']
    end
    part_url
  end

  def new
    @user = User.new
    @user.address = Address.new
  end

  def create
    @user = User.new(user_credentials)

    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_credentials)
        format.html { redirect_to user_images_path(@user.id), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def check_access
      unless @user == current_user || current_user.is_admin?
        redirect_to root_path, :alert => "Access denied."
      end
    end

    def user_credentials
      params.require(:user).permit(:first_name, :last_name, :email, :age, :sex, :about,
                                   address_attributes: [:zip, :city, :street, :home_number])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favs/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href=<%= users_path%>>Main page</a></li>
    <li class="breadcrumb-item"><a href=<%=user_images_path(@user.id)%>>User images</a></li>
    <li class="breadcrumb-item active" aria-current="page">Favourites images</li>
  </ol>
</nav>

<h1 class="text_center">List of your favourites images</h1>

<div class="row">
  <% @all_urls.each do |x| %>
    <div class="col-sm-3">
      <div class="card" style="width: 18rem;">
        <%= image_tag(x.url, class: 'image', width: "auto", height: "auto") %>
        <div class="card-body">
          <h5 class="card-title text_center">Good picture for <%= @user.first_name %></h5>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/favs/index.html.haml
%center
  %h1 List of your favourites images
%h3
  Name: #{@user.name}
%h3
  Lastname: #{@user.lastname}
%h3
  Email: #{@user.email}
- @all_urls.each do |x|
  = image_tag(x.url, class: 'image', width: "300", height: "300")

app/views/images/index.html.erb
<nav aria-label="breadcrumb" class="fixed-bottom bg-dark">
  <ol class="breadcrumb bg-dark">
    <li class="breadcrumb-item"><a href=<%= users_path%>>Main page</a></li>
    <li class="breadcrumb-item active" aria-current="page">Images for <%= @user.first_name%> <%= @user.last_name%></li>
  </ol>
</nav>

<div class="pos-f-t bg-dark">
<!--  <div class="bg-dark p-4">-->
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="pageCenter">
        <table>
          <tbody>
          <tr>
            <td>
              <h5 class="text-white h4">Personal information</h5>
              <h6 class="text-muted">Name: <%= @user.first_name%></h6>
              <h6 class="text-muted">Lastname: <%= @user.last_name%></h6>
              <h6 class="text-muted">Email: <%= @user.email%></h6>
              <%= link_to 'View favourites', user_favs_path(@user.id), class: "btn btn-success" %>
              <%= link_to 'Update profile', edit_user_path(id: @user.id), class: "btn btn-success" %>
              <%= link_to 'Delete profile',  user_path(id: @user.id), method: :delete, class: "btn btn-danger",data: {confirm: 'Are you sure?'} %>
            </td>
            <td>
              <img src=<%= @url%> width="200" height="200" alt="random_image">
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
<!--  </div>-->
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

<div class="row">
  <% @all_urls.each do |x| %>
    <div class="col-sm-3">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src=<%= x.image_url %> alt="Card-image-cap">
        <div class="card-body">
          <table>
            <tbody>
              <tr>
                <td>
                  <h5 class="card-title">User ID: <%= x.user_id %></h5>
                  <p class="card-text">Image ID: <%= x.id %></p>
                </td>
                <td>
                  <div class="btn-group-vertical" role="group" aria-label="Basic example">
                    <%= link_to 'Go to main', users_path, method: :get, class: "btn btn-primary" %>
                    <%= link_to 'Add to favourites', user_image_path(user_id: x.user_id, id: x.id), method: :put, class: "btn btn-success" %>
                    <%= link_to 'Destroy',  user_image_path(user_id: x.user_id, id: x.id), method: :delete, class: "btn btn-danger",data: {confirm: 'Are you sure?'} %>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/images/index.html.haml
%center
  %h1 Your random image
%h3
  Name: #{@user.name}
%h3
  Lastname: #{@user.lastname}
%h3
  Email: #{@user.email}
%center
  %img{:src => "<haml_loud"}/
  @url alt="random_image"&gt;
%center
  %h1 All your images
%center
  %table{:border => "1"}
    %thead
      %tr
        %th Image id
        %th Image
        %th Add to favourites
        %th Delete
    %tbody
      - @all_urls.each do |x|
        %tr
          %td= x.id
          %td= image_tag(x.image_url, class: 'image', width: "300", height: "300")
          %td= link_to 'Add to favourites', user_image_path(user_id: x.user_id, id: x.id), method: :put
          %td= link_to 'Destroy',  user_image_path(user_id: x.user_id, id: x.id), method: :delete, data: {confirm: 'Are you sure?'}
/ "/users/"+x.user_id.to_s+"/images/"+x.id.to_s

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserImageClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand" href=<%= root_path %>>UserImageClub</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <% if current_user %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-success" %>
          <% else %>
              <%= link_to "Login", new_user_session_path, class: "btn btn-success" %>
              <%= link_to "Registration", new_user_registration_path, method: :get, class: "btn btn-success" %>
          <% end %>
        </form>
<!--          <p class="notice"><%#= notice %></p>-->
<!--          <p class="alert"><%#= alert %></p>-->
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title UserImageClub
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/_user_form.html.erb
<%= form_for(user, html: {class: "form-horizontal center"}) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-horizontal center">
    <div class="form-group row form-inline justify-content-center">
      <%= form.label :first_name, class: "col-1 col-form-label", for:"example-text-input" %>
      <div class="col-4">
        <%= form.text_field :first_name, class: "form-control", id: "example-text-input" %>
      </div>

      <%= form.label :last_name, class: "col-1 col-form-label" %>
      <div class="col-4">
        <%= form.text_field :last_name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-horizontal center">
    <div class="form-group row form-inline justify-content-center">
      <%= form.label :email, class: "col-1 col-form-label" %>
      <div class="col-4">
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <%= form.label :age, class: "col-1 col-form-label" %>
      <div class="col-4">
        <%= form.text_field :age, class: "form-control" %>
      </div>
    </div>
  </div>

  <hr>

  <div class="form-horizontal center">
    <div class="form-group row form-inline justify-content-center">
      <%= form.label :Sex, class: "col-1 col-form-label" %>
      <div class="col-4">
        <%= form.select :sex, options_for_select(%w(Male Female Other), 'Male'), class: "form-control" %>
      </div>

      <%= form.label :about, class: "col-1 col-form-label" %>
      <div class="col-4">
        <%= form.text_area :about, class: "form-control" %>
      </div>
    </div>
  </div>

  <hr>

  <%= form.fields_for :address, @user.address do |address_form| %>
    <div class="form-horizontal center">
      <div class="form-group row form-inline justify-content-center">
        <%= address_form.label :zip, class: "col-1 col-form-label"%>
        <div class="col-4">
          <%= address_form.text_field :zip, class: "form-control" %>
        </div>

        <%= address_form.label :city, class: "col-1 col-form-label"%>
        <div class="col-4">
          <%= address_form.text_field :city, class: "form-control"%>
        </div>
      </div>
    </div>

    <div class="form-horizontal center">
      <div class="form-group row form-inline justify-content-center">
        <%= address_form.label :street, class: "col-1 col-form-label"%>
        <div class="col-3">
          <%= address_form.text_field :street, class: "form-control"%>
        </div>

        <%= address_form.label :home_number, class: "col-2 col-form-label"%>
        <div class="col-4">
          <%= address_form.text_field :home_number, class: "form-control"%>
        </div>
      </div>
    </div>
  <% end %>

  <hr>

  <div class="form-horizontal center">
    <div class="actions form-inline justify-content-center">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="bg">
<h1>Update information of user</h1>

<%= render 'user_form', user: @user %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<% if current_user != nil && current_user.is_admin?%>

  <div class="container-fluid">
    <div class="row">
      <div class="col-2">
        <%= form_tag :users, method: :get do%>
          <%= submit_tag "Sort by" %>
          <%= select_tag(:sort_by_names, options_for_select([['firstname', 1], ['lastname', 2]]), class: 'custom-select custom-select-sm select_width') %>
        <%end %>
      </div>

      <div class="col-2">
        <%= form_tag :users, method: :get do%>
          <%= submit_tag "Filter by" %>
          <%= select_tag(:sort_by_cities, options_for_select(@addr), class: 'custom-select custom-select-sm select_width') %>
        <%end %>
      </div>

      <div class="col-3">
        <%= form_tag :users, method: :get do%>
          <%= submit_tag "Filter by" %>
          <%= label_tag 'Male', nil, class: 'badge badge-info' %>
          <%= check_box_tag 'Male', 'Male', class: 'custom-checkbox' %>
          <%= label_tag 'Female', nil, class: 'badge badge-info' %>
          <%= check_box_tag 'Female', 'Female' %>
          <%= label_tag 'Other', nil, class: 'badge badge-info' %>
          <%= check_box_tag 'Other', 'Other' %>
        <%end %>
      </div>

      <div class="col-5">
        <%= form_tag :users, method: :get do%>

          <table>
            <tr>
              <td><%= submit_tag "Filter by age" %></td>
              <td><%= text_field_tag 'from', nil, placeholder: 'From...', class: 'form-control'%></td>
              <td><%= text_field_tag 'to', nil, placeholder: 'To...', class: 'form-control' %></td>
            </tr>
          </table>
        <%end %>
      </div>
    </div>
  </div>

<table class="table table-striped table-dark">
  <thead>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Age</th>
    <th>Sex</th>
    <th>City</th>
    <th>Functionality</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.age %></td>
      <td><%= user.sex %></td>
      <td><%= user.address.city %></td>
      <td>
        <%= link_to 'Show images', user_images_path(user.id), class: "btn btn-outline-primary"%>
        <%= link_to 'Show favourites', user_favs_path(user.id), class: "btn btn-outline-primary"%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% elsif current_user != nil && !current_user.is_admin? %>
  <%= controller.redirect_to user_images_path(current_user.id) %>
<% else %>
  <div class="row">
    <% @all_urls.each do |x| %>
      <div class="col-sm-3">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src=<%= x %> alt="Card-image-cap">
          <div class="card-body">
            <h5 class="card-title">Another good picture for you :)</h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.haml
%h1 List of all users
%table{:border => "1"}
  %thead
    %tr
      %th Name
      %th Lastname
      %th Email
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.lastname
        %td= user.email
        %td= link_to 'Show images', user_images_path(user.id)
        %td= link_to 'Show favourites', user_favs_path(user.id)
%h3
  You can create new user by
  %a{:href => "/users/new"} this link

app/views/users/new.html.erb
<div class="bg">
  <h1>Creation of new user</h1>

  <%= render 'user_form', user: @user %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/new.html.haml
%h1 Creation of new user
= form_with scope: :user, url: users_path, local: true do |form|
  %p
    = form.label :name
    %br/
    = form.text_field :name
  %p
    = form.label :lastname
    %br/
    = form.text_area :lastname
  %p
    = form.label :email
    %br/
    = form.text_area :email
  %p
    = form.submit